### PR TITLE
replaced all "$this->db" to "self::$db" 

### PR DESCRIPTION
**Pull request by Sayak9495**
in accordance with 0005547

### CODE REVIEW

**Comment by Sayak9495** [comment]
@cindyli waiting for your instruction...

**Comment by cindyli** [comment]
Thanks, @Sayak9495. I will verify this PR soon.

**Comment by Sayak9495** [comment]
@cindyli Actually there was another error when using `self::` instead of `this->`, it was throwing an error stating that "Access to undeclared static property" . That's why I've update `private $db;` to `private static $db;`. Now it's working fine on my local machine.

**Comment by cindyli** [comment]
`$this->db` is still used in other scripts. It would be nice to handle all same issues in one pull request. Could you also elaborate the environment, such as PHP and MySQL versions, that you test the pull request against? Thanks.

**Comment by Sayak9495** [comment]
@cindyli Hi, actually there had been some problem with the branch at my end. So I've to delete the branch and push the code once again. Is it fine with you to delete my branch as it will delete this PR as well.

**Comment by cindyli** [comment]
@Sayak9495, feel free to close your own PRs when you need to. It would also be nice to comment with a reason of the close to reduce confusion, if it's possible. Thanks.

**Pull request closed without merging**
