### PR TITLE
 replaced all "$this->db" to "self::$db" 

### PR DESCRIPTION
**Pull request by Sayak9495**
in accordance with 0005547

### CODE REVIEW

**Comment by Sayak9495** [comment]
From Bug Mantis, I got to know about this bug and thought of fixing it as demonstrated there. I'm trying to understand the codebase of AChecker by fixing some of the known issues.

**Comment by cindyli** [comment]
Thanks. Please make sure to test the pull request.

**Comment by Sayak9495** [comment]
Hi @cindyli. How to test the pull request?

**Comment by cindyli** [comment]
I mean to test it locally before submitting the pull request. To make sure the change doesn't break AChecker.

**Comment by Sayak9495** [comment]
Hi. I've opened a new PR #68 . In this PR all the "$this->db" was not updated successfully. And I've checked on my local machine it doesn't break ACheker.

**Comment by cindyli** [comment]
Closed in favor of https://github.com/inclusive-design/AChecker/pull/68.

**Pull request closed without merging**
