### PR TITLE
Updated deprecated mysql functions.

### PR DESCRIPTION
**Pull request by sachinarora707**
Made changes in dump_lang.php

### CODE REVIEW

**Comment by cindyli** [comment]
Thanks for the contribution, @sachinarora707. 

Your fix to dump_lang.php looks good. However, the deprecated mysql functions are used in other scripts too. When fixing an issue in a system, it would be more useful to fix it all across the system instead of fixing a portion and leaving the rest behind.

**Comment by sachinarora707** [comment]
Done. @cindyli Please have a look.

**Comment by cindyli** [comment]
Thanks for completing the pull request, @sachinarora707. Do you get a chance to test?

**Comment by sachinarora707** [comment]
Yes. But, just discovered that there is a variable $addslashes = 'mysql_real_escape_string' in vitals.inc.php. So, I might have left some updations. I'll make the changes and send this PR again.

**Pull request closed without merging**
